name: binder
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - snakemake-minimal
    - sra-tools >2.9.1
    - fastqc ==0.11.9
    - multiqc ==1.10.1
    - bwa ==0.7.17
    - samtools ==1.9
    - picard ==2.20.1
    - salmon ==1.5.1
    - trimmomatic ==0.36
